---
- name: Adding user
  import_playbook: playbook-user.yml

- name: Installing MySQL
  import_playbook: playbook-mysql.yml

- name: Installing Nginx
  import_playbook: playbook-nginx.yml

- name: Installing apps
  hosts: all
  become: true
  vars_files:
    - vars/wordpress_vault.yml    
  roles:   
    - { role: php,  tags: [php, apps] }
    - { role: wordpress, tags: [wp, apps] }

- name: Do some tests
  import_playbook: playbook-tests.yml

- name: Create dir and file with date inside
  import_playbook: playbook-date.yml



  #- name: Prepare user
  #  hosts: server
  #become: true
  #roles:
  #  - { role: user, tags: [prepare] }

  #- name: Add apps
  #hosts: all
  #become: true
  #vars_files:
  #  - vars/wordpress_vault.yml    
  #roles:   
  #  - { role: mysql, tags: [mysql, apps] }
  #  - { role: geerlingguy.nginx, tags: [nginx, apps] }
  #  - { role: php,  tags: [php, apps] }
  #  - { role: wordpress, tags: [wp, apps] }

  #- name: Do some tests
  #hosts: all
  #become: true
  #vars_files:
  #  - vars/wordpress_vault.yml
  #roles:
  #  - { role: tests, tags: [tests] }

